services:
  db:
    image: mysql:8.0
    container_name: mysql-db
    restart: unless-stopped

    environment:
      MYSQL_DATABASE: appdb
      MYSQL_USER: appuser
      MYSQL_PASSWORD: pass123
      MYSQL_ROOT_PASSWORD: pass123

    ports:
      - "3307:3306"

    volumes:
      - mysql-data:/var/lib/mysql
      - ./script.sql:/docker-entrypoint-initdb.d/script.sql

    networks:
      - sameNetworkAsMysql

  api:
    build:
      context: ./backend
      dockerfile: Dockerfile

    container_name: backend-api
    restart: unless-stopped

    ports:
      - "3000:3000"

    depends_on:
      - db

    networks:
      - sameNetworkAsMysql

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile

    container_name: frontend-app
    restart: unless-stopped

    ports:
      - "3001:3000"

    depends_on:
      - api

    networks:
      - sameNetworkAsMysql

networks:
  sameNetworkAsMysql:
    driver: bridge

volumes:
  mysql-data:
